name: Lint Swagger

on:
 push:
      paths:
      - "task/swagger.yaml"
        
jobs:
    setup-lint:
        name: Setup
        runs-on: ubuntu-latest
        steps:
            - name: setup Node environment
              uses: actions/setup-node@v1
              with:
               node-version: '12'
               
            - name: Checkout
              uses: actions/checkout@v2

            - name: install spectral
              run: npm install -g @stoplight/spectral

            - name: Lint
              run: spectral lint task/swagger.yaml
