name: Lint Swagger

on:
  push:
      paths:
      - "task/swagger.yaml"
        
jobs:
    setup-lint:
        name: Lint swagger
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node Environment
              uses: actions/setup-node@v1
              with:
               node-version: '12'
               
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install spectral
              run: npm install -g @stoplight/spectral

            - name: Lint swagger
              run: spectral lint task/swagger.yaml
