name: Lint Swagger

env:

on:
    push:
        jobs:
            setup-lint:
                name: Setup
                runs-on: ubuntu-latest
                steps:
                    - name: npm install
                    run: |
                      npm install -g @stoplight/spectral .
                    
                    - name: Lint
                    run: |
                      spectral lint task/swagger.yaml